15AjaxMVCDemos-master/AjaxMVCDemos/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AjaxMVCDemos.Models
{
    public class Book
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Author { get; set; }

        public string Content { get; set; }
    }
}

15AjaxMVCDemos-master/AjaxMVCDemos/Models/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;

namespace AjaxMVCDemos.Models
{
    public class BookViewModel
    {
        public static Expression<Func<Book, BookViewModel>> FromBook
        {
            get
            {
                return book => new BookViewModel
                {
                    Id = book.Id,
                    Title = book.Title,
                    Author = book.Author
                };
            }
        }

        public int Id { get; set; }

        public string Title { get; set; }

        public string Author { get; set; }
    }
}

15AjaxMVCDemos-master/AjaxMVCDemos/Models/BooksData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AjaxMVCDemos.Models
{
    using System.Collections.Generic;

    public static class BooksData
    {
        public static List<Book> GetAll()
        {
            return new List<Book>
            {
                new Book
                {
                    Id = 1,
                    Title = "Pro ASP.NET MVC 4",
                    Author = "Adam Freeman",
                    Content = "The ASP.NET MVC 4 Framework is the latest evolution of Microsoft’s ASP.NET web platform. It provides a high-productivity programming model that promotes cleaner code architecture, test-driven development, and powerful extensibility, combined with all the benefits of ASP.NET."
                },
                new Book
                {
                    Id = 2,
                    Title = "Professional ASP.NET MVC 4",
                    Author = "Jon Galloway, Phil Haack, Brad Wilson, K. Scott Allen",
                    Content = "Microsoft insiders join giants of the software development community to offer this in-depth guide to ASP.NET MVC, an essential web development technology."
                },
                new Book
                {
                    Id = 3,
                    Title = "Programming ASP.NET MVC 5",
                    Author = "Nimit Joshi",
                    Content = "This book is a basic introduction to Programming ASP.NET MVC 5, basically for beginners who want to learn complete basic with example of ASP.NET MVC 5."
                },
                new Book
                {
                    Id = 4,
                    Title = "AJAX For Dummies",
                    Author = "Steve Holzner",
                    Content = "AJAX is short for “Asynchronous JavaScript + CSS + DOM + XMLHttpRequest.” Even if you weren’t intimidated before, that tidbit is probably enough to make you reach for the Excedrin. Just reach for Ajax For Dummies instead. With screen shots, actual code and explanations, and live Web sites where you can see Ajax applications doing their thing, it will have you using Ajax to create Web applications that look an act like desktop applications in no time. With Ajax, you can speed up and clean up your Web applications."
                }
            };
        }
    }
}

15AjaxMVCDemos-master/AjaxMVCDemos/Controllers/BooksController.cs
using AjaxMVCDemos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AjaxMVCDemos.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index()
        {
            var data = BooksData
                .GetAll()
                .AsQueryable()
                .Select(BookViewModel.FromBook)
                .ToList();

            return this.View(data);
        }

        public ActionResult Search(string query)
        {
            var result = BooksData
                .GetAll()
                .AsQueryable()
                .Where(book => book.Title.ToLower().Contains(query.ToLower()) ||
                    book.Author.ToLower().Contains(query.ToLower()))
                .Select(BookViewModel.FromBook)
                .ToList();
            return this.PartialView("_BookResult", result);
        }

        public ActionResult ContentById(int id)
        {
            if (!Request.IsAjaxRequest())
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return this.Content("This action can be invoke only by AJAX call");
            }

            var book = BooksData.GetAll().FirstOrDefault(x => x.Id == id);
            if (book == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.Content("Book not found");
            }
            return this.Content(book.Content);
        }

    }
}

15AjaxMVCDemos-master/AjaxMVCDemos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxMVCDemos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

15AjaxMVCDemos-master/AjaxMVCDemos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

15AjaxMVCDemos-master/AjaxMVCDemos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

15AjaxMVCDemos-master/AjaxMVCDemos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

15AjaxMVCDemos-master/AjaxMVCDemos/Views/Shared/_BookResult.cshtml
@using System.Activities.Expressions
@model IEnumerable<AjaxMVCDemos.Models.BookViewModel>

@if (Model.Any())
{
    foreach (var book in Model)
    {
        <h3>@book.Title (by @book.Author)</h3>
        @Ajax.ActionLink("See content", "ContentById", "Books", new { id = book.Id },
            new AjaxOptions
                {
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "book-content-" + book.Id
                })
        <div id="book-content-@book.Id"></div>
    }
}
else
{
    <br />
    <div>No matches</div>
}

15AjaxMVCDemos-master/AjaxMVCDemos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>